DB_DATABASE="fu-test"
DB_HOST="127.0.0.1"
DB_USERNAME="root"
DB_PASSWORD="root"
DQ='\"'

# $1=csvPath $2=tb
QUERY="LOAD DATA LOCAL INFILE ~/$1 INTO TABLE $2 CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '$DQ' LINES TERMINATED BY '\\\n' IGNORE 1 ROWS;"
echo mysql -h $DB_HOST -u $DB_USERNAME -p -e "$QUERY"


